# Legit Workflow Configuration

# Input/Output settings
input_directory: "content"
output_directory: "pdfs"
file_pattern: "*.md"  # Which markdown files to process

# Specific files to always include (even if they don't match the pattern)
include_files:
  - "content/example-paper.md"
  - "content/simple-test.md"

# Template settings
template_file: "templates/scientific-paper.tex"
scientific_template_file: "templates/scientific-paper.tex"
academic_template_file: "templates/academic-paper.tex"
technical_report_template_file: "templates/technical-report.tex"
preprint_template_file: "templates/preprint.tex"
thesis_template_file: "templates/thesis.tex"

# Image settings
images_directory: "figures"

# PDF engine
pdf_engine: "xelatex"

# Additional LaTeX packages to install
additional_packages:
  - "lmodern"
  - "microtype"
  - "amsmath"
  - "amssymb"
  - "mathtools"
  - "physics"
  - "fancyhdr"
  - "graphicx"
  - "adjustbox"
  - "rotating"
  - "pdflscape"
  - "float"
  - "booktabs"
  - "longtable"
  - "array"
  - "multirow"
  - "tabularx"
  - "threeparttable"
  - "hyperref"
  - "cleveref"
  - "biblatex"
  - "listings"
  - "algorithm"
  - "algpseudocode"
  - "xcolor"
  - "caption"

# Format-specific settings
formats:
  scientific:
    enabled: true
    header-includes:
      - "\\usepackage{physics}"
      - "\\usepackage{siunitx}"
      - "\\usepackage{mathtools}"
      - "\\usepackage{amsmath,amssymb}"
      - "\\usepackage{algorithm}"
      - "\\usepackage{algpseudocode}"
      - "\\usepackage{booktabs}"
      - "\\usepackage{longtable}"
  academic:
    enabled: true
    header-includes:
      - "\\usepackage{physics}"
      - "\\usepackage{mathtools}"
      - "\\usepackage{amsmath,amssymb}"
  technical-report:
    enabled: true
    header-includes:
      - "\\usepackage{tcolorbox}"
      - "\\usepackage{tikz}"
      - "\\usepackage{mdframed}"
  preprint:
    enabled: true
    header-includes:
      - "\\usepackage{tcolorbox}"
      - "\\usepackage{physics}"
      - "\\usepackage{mathtools}"
  thesis:
    enabled: true
    header-includes:
      - "\\usepackage{tocloft}"
      - "\\usepackage{titlesec}"
      - "\\usepackage{physics}"
      - "\\usepackage{mathtools}"
