# Workflow Configuration File
# This file defines the configuration parameters for the Markdown to PDF GitHub workflow

# General settings
general:
  # Whether to run the workflow in debug mode (provides more verbose output)
  debug: false
  # The timezone to use for date formatting in generated PDFs
  timezone: "UTC"
  # Whether to create an index file listing all generated PDFs
  create_index: true

# Input settings
input:
  # Directory containing markdown files to process
  content_dir: "content"
  # File pattern to match markdown files (use globbing pattern)
  file_pattern: "*.md"
  # Specific files to always include (even if they don't match the pattern)
  include_files:
    - "content/example-paper.md"
  # Files to exclude (even if they match the pattern)
  exclude_files:
    - "README.md"

# Output settings
output:
  # Directory to store generated PDFs
  pdf_dir: "pdfs"
  # Directory for any intermediate files (e.g., temporary LaTeX files)
  temp_dir: ".tmp"
  # Format for timestamped versioning of PDFs
  timestamp_format: "%Y%m%d-%H%M%S"
  # Whether to keep a "latest" version of each PDF without timestamp
  keep_latest: true
  # Whether to keep the original filenames or transform them
  # Options: "original", "lowercase", "kebab-case"
  filename_format: "original"

# Template settings
template:
  # Directory containing LaTeX templates
  template_dir: "templates"
  # Default LaTeX template to use
  default_template: "scientific-paper.tex"
  # Map of markdown files to specific templates (if different from default)
  file_templates:
    # "content/special-paper.md": "special-template.tex"

# Asset settings
assets:
  # Directory containing images and other assets
  figures_dir: "figures"
  # Whether to embed images directly in PDFs or link them
  embed_images: true
  # Default DPI for rasterized images
  image_dpi: 300
  # Supported image formats
  supported_formats:
    - ".png"
    - ".jpg"
    - ".jpeg"
    - ".svg"
    - ".pdf"

# LaTeX settings
latex:
  # LaTeX engine to use with Pandoc
  # Options: "pdflatex", "xelatex", "lualatex"
  engine: "xelatex"
  # Additional LaTeX packages to include
  additional_packages:
    - "microtype"
    - "booktabs"
  # Bibliography settings
  bibliography:
    # Whether to process citations
    enabled: true
    # Citation style (e.g., APA, IEEE, etc.)
    style: "ieee"
    # Default .bib file to use if not specified in markdown frontmatter
    default_bibfile: "references/bibliography.bib"

# S3 upload settings
s3_upload:
  # Whether to upload PDFs to S3
  enabled: true
  # Base path in the S3 bucket 
  base_path: "papers"
  # Whether to organize PDFs in subdirectories by date
  organize_by_date: true
  # ACL for uploaded objects
  # Options: "private", "public-read", "public-read-write", "authenticated-read"
  acl: "public-read"
  # Cache control settings for S3 objects
  cache_control: "max-age=86400"
  # Content type for PDFs
  content_type: "application/pdf"

